name: Smoke playwright-report zip
# (To use it change the reporter in the playwright.config.ts to playwright-report)

on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Chromium Only
        run: npx playwright install chromium
      - name: Run Playwright Smoke Tests on Chrome Only
        run: npx playwright test --project=chromium --grep @smoke

      - name: Debug - show report folder
        run: |
          echo "Exit code of previous command: $?"
          pwd
          ls -la
          ls -la playwright-report || echo "playwright-report not found"
          find playwright-report -maxdepth 3 -type f -print || true

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
